name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  releaseBuild:
    name: Release Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup ghr
        run: |
          wget -O ghr.tar.gz https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz
          tar xvzf ghr.tar.gz; rm ghr.tar.gz
          sudo mv ghr*linux_amd64/ghr /usr/local/bin; rm -rf ghr*linux_amd64
      - name: assembleRelease
        run: |
          export LOCAL_PROPERTIES="${{ secrets.LOCAL_PROPERTIES }}"
          ./gradlew TMessagesPro:assembleRelease \
                    TMessagesProj:assembleReleaseNoGcm \
                    TMessagesProj:bundleAfatRelease
      - name: Upload apks
        run: |
          sudo apt install -y rename
          export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          mkdir apks; find . -name "*.apk" -exec mv {} apks \;
          rename "s/TMessagesProj/NekoX/" apks/*
          ref="${{ github.ref }}"
          ref=${ref/"refs/tags/"/}
          msg="${{ github.event.head_commit.message }}"
          ghr -delete -n "$ref" -b "$msg" "$ref" apks/
      - uses: r0adkll/upload-google-play@master
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_ACCOUNT_SERVICE }}
          packageName: nekox.messenger
          releaseFile: "TMessagesProj/build/outputs/bundle/afatRelease/TMessagesProj-afat-release.aab"
          track: production
        if: "!startsWith(github.event.head_commit.message, '!!')"